Cargo.lock, Cargo.toml, src/core/kernel_symbols.rs, src/core/mod.rs, src/main.rs
Simple interface to get kernel symbols addresses from their name and the opposite. This will be useful for probing the kernel, from configuring kprobes to understanding where an event is coming from.
=> core: add a kernel_symbol module

Cargo.lock, Cargo.toml, build.rs, src/core/probe/kernel/bpf/include/common.h, src/core/probe/kernel/config.rs, src/core/probe/kernel/mod.rs
The two first commits are small fixes.
The last one extends the runtime inspection of symbols (functions/tracepoints) to dynamically check if given parameters are available and if so to provide their offsets to the BPF probes.
The extra information is then used in BPF to add helpers to easily retrieve known parameters, e.g.
```
struct sk_buff *skb = trace_get_sk_buff(ctx);
if (!skb)
return 0;
[...]
```
Current known parameters: `struct sk_buff *`, `enum skb_drop_reason`, `struct net_device *`, `struct net *`.
An helper is also added for collectors to inspect function & tracepoints at runtime, e.g.
```
let skb = kernel.function_parameter_offset(ProbeType::Kprobe, "skb_free_reason", "struct sk_buff *")?.is_some();
```
Based on #22 .
=> Extend probe runtime inspection and provide parameter offsets

src/core/probe/kernel/kernel.rs, src/core/probe/kernel/kprobe.rs, src/core/probe/kernel/raw_tracepoint.rs
With this collectors can register maps and let their hooks reuse the maps fds. This will help in having per-collector/hook maps for retrieving specific information or retrieving configuration in the BPF part.
=> Allow hooks to reuse their own maps

Cargo.lock, Cargo.toml, build.rs, src/collector/collector.rs, src/collector/mod.rs, src/collector/ovs/ovs.rs, src/collector/skb/skb.rs, src/collector/skb_tracking/bpf/tracking_hook.bpf.c, src/collector/skb_tracking/mod.rs, src/collector/skb_tracking/skb_tracking.rs, src/core/mod.rs, src/core/probe/kernel/inspect.rs, src/core/probe/kernel/kernel.rs, src/core/probe/kernel/kprobe.rs, src/core/probe/kernel/mod.rs, src/core/probe/kernel/raw_tracepoint.rs, src/core/workaround.rs
This adds a collector which will track skbs and generate a unique id so we can recognize a collector later in the stack and reconstruct its life at post-processing time (or manually looking at the events; once available).
Some extra commits to make the tracking collector easier to implement. More info in the commit themselves.
Based on #50.
=> Track skbs using a dedicated collector

build.rs, src/core/events/bpf.rs, src/core/events/bpf/include/events.h, src/core/events/events.rs, src/core/probe/kernel/bpf/include/common.h, src/core/probe/kernel/config.rs, src/module/skb/bpf.rs, src/module/skb/bpf/skb_hook.bpf.c, src/module/skb/mod.rs, src/module/skb/skb.rs, src/module/skb_tracking/bpf/tracking_hook.bpf.c, src/module/skb_tracking/skb_tracking.rs
Let's put an emphasis on *initial*:
- Logic to retrieve more data, and/or to get some data from other sources can and will be added later.
- Event field names might change.
- There are probably some corner cases not supported, e.g. probing certain functions means parts of the skb wasn't processed yet and accessing this data might not be possible (w/o implementing a full packet parser) or not set yet fields resulting in invalid data[1].
However I believe this PR is in a good shape to provide an example of what data collection from a module should look like and might trigger some discussions; and good enough to be used already for retrieving common fields in well known L2 to L4 protocols as well as from the skb metadata.
[1] So far I put measures in place to fix the one I know and found.
=> Initial support for skb data retrieval (aka skb module events)

src/core/kernel/btf.rs, src/core/kernel/inspect.rs, src/module/module.rs, src/module/skb_drop/event.rs, src/module/skb_drop/skb_drop.rs
This has multiple advantages:
- Ease to understand the reason why a packet was dropped.
- Better compatibility with different kernel versions.
Example:
```
{"common":{"timestamp":3748134824705},"kernel":{"probe_type":"kprobe","symbol":"kfree_skb_reason"},"skb-drop":{"drop_reason":"tcp old data"}}
{"common":{"timestamp":3748134840945},"kernel":{"probe_type":"kprobe","symbol":"kfree_skb_reason"},"skb-drop":{"drop_reason":"not specified"}}
{"common":{"timestamp":3748223136046},"kernel":{"probe_type":"kprobe","symbol":"kfree_skb_reason"},"skb-drop":{"drop_reason":"tcp invalid sequence"}}
{"common":{"timestamp":3903142678490},"kernel":{"probe_type":"kprobe","symbol":"kfree_skb_reason"},"skb-drop":{"drop_reason":"no socket"}}
```
Based on #102.
=> Use a text format for drop reasons in events

src/core/probe/kernel/bpf/include/common.h, src/core/probe/kernel/bpf/include/helpers.h, src/core/probe/kernel/bpf/kprobe.bpf.c, src/core/probe/kernel/bpf/kretprobe.bpf.c
When CONFIG_X86_KERNEL_IBT=y an endbr instruction at the function entry is added, resulting in IP being +4 further. Add a conditional to select the right offset to subtract from PT_REGS_IP when retrieving the function IP (ksym).
A future work could be to use bpf_get_func_ip instead, but that isn't supported in all kernel versions so it should be done with care.
=> core: probe: kernel: kprobe: fix ksym retrieval for CONFIG_X86_KERNEL_IBT=y

src/core/filters/packets/ebpfinsn.rs
as reported in #138 by @amorenoz, the build fails using rustc 1.65.
This happens because custom discriminant values are not allowed in enums with tuple or struct variants in rust in versions < 1.66 which is of course the one we need :)
Fix it by removing the discriminant as it was fundamentally introduced for consistency.
=> fix build with rustc 1.65

src/core/probe/kernel/bpf/include/common.h, src/module/nft/bpf/nft.bpf.c
This comes from the following issue: when nft module is used, we'll see many events reported from `__nft_trace_packet`. We can filter the nft section out, by using `--nft-verdicts` but since other hooks are attached we will still see all the events, just not all will contain an nft section. We could use `ProbeOption::NoGenericHook` but then we loose valuable information such as tracking-id or skb data when events are reported.
The real solution is to add an nft filter, and let the user select whether an AND or an OR is wanted (to support tracking packets only when after a given verdict was seen, or to track packets including when they trigger a given verdict). It's not as simple as that because there are actually two AND versions (only when the data is available or always?).
In the …
=> Allow hooks to discard the event

src/cli/cli.rs
Based on #75 with an extra commit.
Instead of only reporting the package version, also report the git HEAD information. This is useful as the Rust package version isn't directly linked to git information (tag, commit, etc) and the same version could be reported for different states of the project. This will help in supporting users to ensure the version points to a real state of the project.
The drawback is this information is retrieved in `build.rs` and the logic re-triggers the full `build.rs` for every `.git/HEAD` change. IMHO this is fine as we'll just force a rebuild when switching branches and/or adding new commits, but not for every development iterations.
Thoughts?
=> Allow reporting the version in the cli

tools/retis_in_container.sh
Otherwise multi-word filters cannot be used.
=> tools: retis_in_container.sh: preserve quotes in retis args

src/module/skb/bpf.rs, src/module/skb/bpf/skb_hook.bpf.c, src/module/skb/event.rs
Retrieving information from `skb->dev` is tricky as this is inside an union and there is no way we can know of the data is valid. Try our best to report an empty section if the data does not look like what it should.
=> module: skb: do not fail on invalid net device information

src/cli/cli.rs
Fixes #221. 
As far as I can tell the issue should apply to all versions of Retis, not just those build on copr. The issue is that try_get_matches_from() returns an error for --help and --version arguments which bubbles up through the ?, leading main() to exit early.
The version and help information currently being shown is actually the formatted error message of either ErrorKind::DisplayHelp or ErrorKind::DisplayVersion being printed by the rust runtime upon main() exiting.
All the other command processing behavior should be preserved because ignore_errors() made it so that only help and version options were being caught by try_get_matches_from() anyway.
=> cli: fix error messages on --help and --version

.mailmap
The current one was covering the GH generated email, but an additional one is needed to cover the different writings of the @redhat.com ones.
I chose the current way of writing your name (w/o the accent), but of course it's your choice and we can use the real one :)
=> mailmap: add one more entry for Adrián

profiles/generic.yaml, src/core/tracking/skb_tracking.rs
Properly taking care of the `net:net_dev_xmit` tracepoint, which can access already freed skbs.
Before this PR, tracking entries were being removed by the tracking gc when using a probe on `net:net_dev_xmit`, like the `generic` profile does.
=> skb tracking improvements / fixes

.gitignore, src/collect/cli.rs, src/core/events/file.rs, src/process/cli/print.rs, src/process/cli/sort.rs
Reverts retis-org/retis#266
This introduced a requirement for the `--out` parameter to use `=` when setting a value, which we find not practical. The other commits are OK but for now let's revert all those patches and spend some time to think about what could be done and do better tests.
=> Revert "Default the event file to retis.data"

Cargo.lock, Cargo.toml
Only one incompatible change: nix stopped enabling features by default, so had to enable the ones we use by hand.
=> Cargo.toml: update dependencies

Cargo.lock, Cargo.toml, profiles/pcap.yaml, src/cli/cli.rs, src/core/kernel/symbol.rs, src/module/skb/bpf.rs, src/module/skb/bpf/skb_hook.bpf.c, src/module/skb/event.rs, src/module/skb/skb.rs, src/process/cli/mod.rs, src/process/cli/pcap.rs, tools/retis_in_container.sh
Fixes #224. Marking as RFC to get avoid merging it while waiting for feedback; but code is in a good shape.
Two majors changes:
1. The `skb` module gained support for reporting raw packets from the BPF probes. This is disabled by default and enabled by using the `--skb-sections packet` option (note the recommendation and what is used in the new `pcap` profile is `packet,dev,ns`).
2. A post-processing command was added, `pcap`, to generate a `pcap-ng` formatted output (stdout or a file) from a *single* probe. This probe is selected at post-processing time (a single set of collected events can be used to generate different pcap outputs).
The pcap-ng output includes a definition of net devices seen in the events, including a name of the form `<name> (<netns>)` and a description of the form …
=> pcap-ng support

src/core/probe/kernel/bpf/include/helpers.h, src/module/skb/bpf/skb_hook.bpf.c
Validating offsets in an skb is no easy task. Add helpers to make checks more consistent in our probes and do the best we can do to guess if offsets are valid or not.
Note that this cannot be 100% failsafe. When converting Retis to parse packets in the Rust side we'll be able to improve further offset detection by using the BPF side as a hint only.
=> tree: add skb offset validation helpers

profiles/drop.yaml, src/profiles/profiles.rs
Allows to do things like:
```
$ retis -p dropmon,pcap collect -o retis.data
or
$ retis -p generic,pcap collect -o retis.data
```
And then,
```
$ retis -p dropmon pcap retis.data | tcpdump -nnr -
```
=> Allow pcap sub-command in profiles

src/module/skb/bpf.rs, src/module/skb/bpf/skb_hook.bpf.c
Two raw packet capture fixes for when:
- Capture length is the max allowed (was converted to 0...).
- No data lies in the skb linear buffer part.
=> Raw packet capture fixes

src/collect/cli.rs, src/collect/collector.rs, src/core/inspect/kernel.rs, src/core/kernel/symbol.rs
Currently Retis supports `--probe kprobe:tcp_*` but not for `kretprobe` nor `tp`. This PR adds support for those.
=> Allow all (user defined) probe types to be defnied using wildcard

src/module/ovs/bpf/kernel_exec_actions.bpf.c, src/module/ovs/bpf/kernel_upcall_tp.bpf.c
With the upcoming Linux v6.8 and commit c871d0e00f0e ("bpf: enforce precise retval range on program exit") returned value of programs are enforced to be in specific ranges. For tracepoints the range is [0, 0]; meaning programs should always return 0.
This is an issue in Retis as we load hooks as programs and they sometimes return non-0 values. When this happens and the hook is used in a raw tracepoint, the following error message is issued:
At program exit the register R0 has smin=-1 smax=-1 should have been in [0, 0]
So far only a single hook is problematic, kernel_upcall_tp. For completeness, this patch also converts other kernel hooks to not return custom values. This fixes our runtime CI tests on Rawhide.
This alone is not sufficient. While returning custom errors is problematic even …
=> module: ovs: fix return value in raw tracepoint program

Cargo.lock, Cargo.toml, docs/install.md, src/cli/cli.rs, src/collect/cli.rs, src/generate/completion.rs, src/generate/mod.rs, src/main.rs
As the clap_complete dynamic module is unstable and hard-codes the
subcommand as `complete`, which conflicts with the current `collect`
subcommand. Let's still use the legacy static way to generate the
completion file.
Usage:
$ retis generate -h
Generate completions file for a specified shell
Usage: retis generate [OPTIONS]
Options:
--shell <SHELL>        Specify shell to complete for [possible values: bash, elvish, fish, powershell, zsh]
--register <REGISTER>  Path to write completion-registration to
-h, --help                 Print help
$ retis generate --shell bash --register .
$ source retis.bash
Close: #68
---
v5: Remove `fn thin()` from `impl SubCommand`. Update doc description.
v4: Update docs/install.md about how to auto-complete. Fix `collect` subcommand auto-completion.
v3: …
=> cli: add shell completion subcommand

retis-derive/src/lib.rs, src/collect/cli.rs, src/collect/collector.rs, src/core/events/display.rs, src/core/events/events.rs, src/core/probe/kernel/kernel.rs, src/core/probe/kernel/mod.rs, src/core/probe/kernel/probe_stack.rs, src/core/probe/manager.rs, src/core/probe/mod.rs, src/core/probe/user/user.rs, src/core/tracking/skb_tracking.rs, src/module/ct/ct.rs, src/module/nft/nft.rs, src/module/ovs/ovs.rs, src/module/skb/skb.rs, src/module/skb_drop/skb_drop.rs, src/module/skb_tracking/skb_tracking.rs
This enables collection to use a new "auto-probe" mode, working as follow: stack traces are requested and functions found in those stack traces are evaluated and additional probes are added if they fit the requirements. Using this mode can help building a list of probes to use for following a given flow. More details about the implementation in the commit messages.
Part of this series is another rework of the probe manager. But fear not, there is no big functional changes and the code is very close to what it was. But the logic is better defined and that allows additional things, such as runtime registration of probes.
This is based on a few patches that are in other PRs (btf-rs update patches mainly). This is fine as they're all targeted at an earlier milestone.
One future possibility is …
=> Auto-probe mode

.cirrus.yml, Cargo.toml, Makefile, Vagrantfile, build.rs, docs/CONTRIBUTING.md, docs/install.md, ebpf.mk, src/cli/cli.rs, src/core/events/bpf.rs, src/core/filters/meta/bpf/include/meta_filter.h, src/main.rs, src/module/ct/bpf/ct.bpf.c, src/module/skb/bpf/skb_hook.bpf.c, tools/benchmark_event_output.sh, tools/benchmark_event_parsing.sh
- build time halved
- finer-grained and better rebuild prereq checks
- clean target actually cleans the tree
- can be easier to use the available tooling (maybe linking progs, if we'll ever use that)
- could be easily extended to build ebpf programs in a container
- ebpf progs can be built independently
- simplifies build.rs (maybe :)
- can make it fairly easy to switch to GCC instead of clang
=> build.rs: split tool and ebpf program build

src/module/ovs/bpf/include/ovs_common.h
The macro is provided by the header we consume.
There's no longer a need to define a local version.
=> Remove no longer needed macro

src/core/probe/bpf/include/common_defs.h, src/core/probe/common.rs, src/core/probe/kernel/bpf/include/common.h, src/core/probe/manager.rs, src/core/probe/user/bpf/usdt.bpf.c
Not doing so lead to various issues such as:
- Inconsistency about what events are reported for a given flow.
- Tracking issues as not all tracking probes are installed (leading to unrelated flows sharing the same tracking id, or stalled entries in the tracking map).
This also opens the door for having other shared configuration options among all probes.
Fixes #312. Includes the same probe manager reworks as #309 but does not depend on it.
=> Wait for all probes to be installed before starting the collection

.cirrus.yml, AUTHORS.md, docs/CONTRIBUTING.md, tools/authors.sh
Add a script to auto-generate and check an AUTHORS.md file and add a CI job to check if the authors file is up-to-date so we don't miss new contributors.
Currently the authors file lists authors based on their git name in alphabetical order, which value depends on how the author configured its git name (could be name, first name, surname, random, etc). Feel free to make any suggestion if you feel this should be done otherwise (by # of commits, first contribution date[1], etc).
[1] Note: using `awk '!x[$0]++'` instead of `sort`.
=> Add an authors file

Makefile, src/core/probe/manager.rs, src/core/probe/probe.rs
Addressed a few warnings (test build) inadvertently introduced in a recent patch and enforces treating warnings as errors to prevent future oversights
=> Treat warnings as errors

src/core/probe/kernel/bpf/include/common.h, src/core/probe/user/bpf/usdt.bpf.c
It seems declaring the variable as volatile is not enough and it was being optimized.
Although it was only observed to be optimized out in the case of usdt probes, we use the exact same mechanism in kernel probes so also adding the barrier there to void discarding events.
Fixes #368
=> probe: add barrier to pass_threshold.

src/module/ovs/bpf/user_recv_upcall.bpf.c
Recent kernels enforce certain return values for ebpf programs.
In the case of USDT probes, it seems this value is zero, so loading the current ovs module fails with:
At program exit the register R0 has smin=-1 smax=-1 should have been in [0, 0]
Fix it by always returning 0.
More information about this here:
682c94be module: ovs: fix return value in raw tracepoint program
Fixes #366
=> module: ovs: do not return -1 on usdt hook.

src/cli/cli.rs, src/collect/cli.rs, src/collect/collector.rs, src/generate/completion.rs
When generating the auto-complete file, we need to get full command parameters after `get_cli()?.build()`. But the collect subcommand only has a default collector setting at the first build round. It only generates all command parameters after running the subcommand specifically.
To generate all the parameters in the first round, we need to update the SubCommand full implementation to register all modules during building. With this, we can auto-complete all collect sub-parameters.
After update, there is no need to register again in command run.
At the same time, since we registered all modules during command build. In testing, if the collector only has a part of the modules, the init will fail with error "unknown collector {}". There is no need to initialize all collectors from args. We …
=> collect: support collect sub command auto complete

.cirrus.yml, RELEASE.md, docs/CONTRIBUTING.md, tools/authors.sh
This makes first contributions easier for people. Also removes the burden from the contributors and makes us update the authors file (using a GH action).
Note that for this to work we must enable `Settings > Actions > General > Workflow permissions > Read and write permissions`. IMO that's OK, but feel free to disagree.
For an example of this in action, see https://github.com/atenart/test. Generated commits look like:
```
Author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Wed Apr 17 12:10:25 2024 +0000
Update authors file
```
=> Some authors file (logical) updates

Cargo.lock, Cargo.toml, src/process/cli/sort.rs
Path-clean is a low-activity simple library that can be imported in our code directly to avoid adding it as a dependency. As we want to package Retis in Fedora we need to reduce the number of dependencies to the minimum possible, otherwise we would need to own and maintain them too in Fedora.
=> process: cli: drop path-clean dependency

Cargo.lock, retis/Cargo.toml, retis/src/module/skb/bpf.rs
pnet is a thin re-export of pnet_base, pnet_sys, pnet_datalink, pnet_transport and pnet_packet.
We only use the last package so pointing directly to it makes our dependency smaller and packaging easier.
=> Cargo.toml: use pnet_packet directly

retis/src/core/filters/meta/bpf/include/meta_filter.h, retis/src/core/filters/meta/filter.rs
Some clean-ups that serve as a preparation for multiple-field matching.
Submitted separately as they make sense regardless.
=> Meta remove unions

retis/src/core/inspect/kernel.rs, retis/src/helpers/bimap.rs, retis/src/helpers/mod.rs
The `bimap` usage can be replaced by a tuple of maps where the first element represent left->right and the sencond one represent right->left.
=> core: inspect: kernel: drop bimap dependency

retis/src/core/events/bpf.rs
While polling the ringbuffer -EINTR can be returned on various occasions. Some are valid reasons to exit the polling thread (^C, running state info from rb handler, etc) but some are not (^Z). We can safely omit explicitly breaking the polling loop as it already depends on Running.
Fixes #397.
Fixes: 95a690e99fdd ("allow to gracefully interrupt the tool.")
=> core: events: bpf: do not exit polling thread on EINTR

Cargo.lock, retis-events/Cargo.toml
As per title, simply drop a dependency.
=> drop rustyline dep

Makefile
Add the warnings flag to RUSTFLAGS globally in the release target to prevent targets depending on this one to build Retis again when executed.
For example `make install` was unconditionally rebuilding Retis even if a release build was done before, this was because the RUSTFLAGS differed between the targets. We now set it for all future targets, so the build states are consistent.
=> Makefile: augment RUSTFLAGS globally in release

Makefile
A dedicated release target was added and the help entry is a bit misleading with that regard.
Update it changing the option in the example.
=> Makefile/help: update outdated entry.

docs/requirements.md
- Update the Kconfig list.
- Remove the mandatory vs option listing. Retis does require all of them and can work in degraded mode if some of them are missing, but that is not advised.
- Remove the obsolete /etc/os-release requirement.
- Add CentOS Stream 8 (>= 8.6) as being supported.
=> docs: requirement: refine page

docs/filtering.md, docs/index.md, mkdocs.yml, retis/src/core/filters/meta/bpf/include/meta_filter.h, retis/src/core/filters/meta/filter.rs
Implements  #317 plus lhs-only expressions.
- Needs unit tests.
- The doc needs some improvements
- pseudo-EBNF requires some improvements (e.g. split numeric and string-only ops)
- alternatively, pseudo-EBNF could be replaced by simple generic examples (which could be easier for the user to use as reference)
Turned into RFC.
Everything is open to discussion including:
- syntax for mask and cast (slight preference to keep it simple :)
- doc (see above)
- have a local version with some tests (I will update as soon as I find some time)
=> Meta adv matches

.cirrus.yml, Vagrantfile
Main goal was to fix the c8s pipeline, which is done by fixing the c8s repo urls. While at it also transitioned to use boxes provided by the upstream projects (Fedora, CentOS Stream); this allows to have more recent images.
=> Fix c8s runtime CI

retis-events/src/ct.rs
CtConnEvent is not an event section, it's an event type embedded into the "ct" event section.
=> events: ct: make CtConnEvent an event_type

retis-events/src/common.rs, retis-events/src/ct.rs, retis-events/src/display.rs, retis-events/src/events.rs, retis-events/src/kernel.rs, retis-events/src/nft.rs, retis-events/src/ovs.rs, retis-events/src/skb.rs, retis-events/src/skb_drop.rs, retis-events/src/skb_tracking.rs, retis-events/src/user.rs, retis/src/collect/collector.rs, retis/src/core/events/bpf.rs, retis/src/process/display.rs, tools/benchmark_event_output.sh, tools/benchmark_event_parsing.sh
Based on #385.
This introduces our own `Formatter` instead of directly using `fmt::Formatter` when constructing the event display result. The main advantage is an improved flexibility where formatting is not done at post-processing but directly while constructing the output. Event sub-sections and types can now decide to output multi-line data.
=> Improve event formatting

retis-derive/src/lib.rs, retis-events/src/common.rs, retis-events/src/ct.rs, retis-events/src/events.rs, retis-events/src/kernel.rs, retis-events/src/nft.rs, retis-events/src/ovs.rs, retis-events/src/skb.rs, retis-events/src/skb_drop.rs, retis-events/src/skb_tracking.rs, retis-events/src/user.rs, retis/src/collect/collector.rs, retis/src/core/events/bpf.rs, retis/src/core/events/bpf/include/events.h, retis/src/core/probe/kernel/kernel.rs, retis/src/core/probe/user/user.rs, retis/src/module/ct/bpf.rs, retis/src/module/ct/ct.rs, retis/src/module/module.rs, retis/src/module/nft/bpf.rs, retis/src/module/nft/nft.rs, retis/src/module/ovs/bpf.rs, retis/src/module/ovs/ovs.rs, retis/src/module/skb/bpf.rs, retis/src/module/skb/skb.rs, retis/src/module/skb_drop/bpf.rs, retis/src/module/skb_drop/skb_drop.rs, retis/src/module/skb_tracking/skb_tracking.rs, retis/src/process/tracking.rs
Semi-RFC material; since code is ready let's not flag it but feel free to discuss the approach :)
The main goal of this series is $title, and some preliminary work for a possible future removal of the module concept. In any way this solve issues linked to how the section ids were used which did not map to the reality:
- Factories are tied to a BPF counterpart, not to an event section. Eg. the tracking section is generated at post-processing time and does not have any link to the BPF side.
- Modules are not strictly tied to event sections. Eg. all core sections do not have a corresponding module.
- Factories and modules are not in a 1:1 relationship. Eg. core factories are not in a module.
This also now allows to have a factory producing more than a single type of event section; this is no …
=> Untangle the section id, factories and modules

.containerignore, .github/workflows/build_push_image.yaml, Containerfile, RELEASE.md
- Modifies `Containerfile` keeping in mind the workspace structure
- while at it, included some clean-ups
- Introduces the creation of a new image based on the current main
- scheduled every 1st of the month
- can be triggered manually
- Simplifies the release process
- RELEASE.md was updated accordingly
- Tokens have been added to the repo settings
Workflow complete run:
- [manual](https://github.com/vlrpl/retis/actions/runs/11386275978/job/31678089186)
- nexttest latest-nexttest
- [scheduled](https://github.com/vlrpl/retis/actions/runs/11384264586/job/31671597581) 
- next
New images generated with the workflow (will be deleted):
https://quay.io/repository/retis/retis?tab=tags
Fixes #291
=> Containerfile and workflow improvements

docs/requirements.md, retis/Cargo.toml, retis/src/cli/cli.rs, retis/src/collect/cli.rs, retis/src/collect/collector.rs, retis/src/generate/completion.rs, retis/src/main.rs
If `debugfs` is not mounted (eg. in containers, namespaces) try mounting it if `--allow-system-changes` is set. The bonus patch is making `retis collect --help` not requiring root privileges.
Closes #402, closes #278.
=> Try mounting debugfs if not there + a bonus patch

mkdocs.yml
Currently, "Edit on GitHub" links points to the wrong "master" branch so use "main" branch instead.
See https://github.com/mkdocs/mkdocs/issues/1578#issuecomment-410836503
=> docs: Fix "Edit on GitHub" links

.cirrus.yml, docs/CONTRIBUTING.md
=> doc: introduce code coverage section

retis/src/helpers/logger.rs, retis/src/helpers/pager.rs, retis/src/process/display.rs
- Auto detect if we should output colors or not.
- Fix EPIPE handling when writing to stdout.
=> Some terminal output improvements

retis-events/src/display.rs
When a newline is found at the end of the buffer it was printed twice. This is because splitting such string will result in having an empty last split. The logic was then printing a new line for the split and because one was at the end of the buffer.
This also prevents from printing the prefix and fixes cases where a double newline is found in the middle of the buffer.
=> events: formatting: fix newline at end of buffer handling

retis-events/src/ct.rs, retis-events/src/helpers.rs, retis-events/src/lib.rs, retis-events/src/skb.rs, retis/src/bindings/ct_uapi.rs, retis/src/core/probe/kernel/bpf/include/helpers.h, retis/src/module/ct/bpf.rs, retis/src/module/ct/bpf/ct.bpf.c, retis/src/module/skb/bpf.rs
RFC as I don't want this to be merged before the bindgen PR (#419); this will need to be rebased.
A test image is available and can be used as follow:
```
$ RETIS_TAG=ct-mark-label ./retis_in_container.sh collect -c ct ...
```
Labels can be set for testing, eg:
```
$ iptables -A INPUT -m connlabel --label 42 --set
```
A few questions / remarks:
- I took the opportunity to make the parent ct information to be printed on a newline. Is that understandable?
- Both the mark and labels are retrieved for the base *and* the parent `nf_conn`.
- Labels are a bitmask; I chose to print them as an hex value to save some space. Is that fine?
@igsilya can you help testing to make sure this looks good? Thanks!
Close #407.
=> ct: add support for mark and labels

retis/src/collect/collector.rs
Small UX enhancement providing feedback on termination showing the number of processed events.
More and fancy counters could be chased (raw events received but not stored and so forth) but that would be out of scope.
=> collector.rs: count and display processed events

docs/install.md, tools/retis_in_container.sh
Added an environment variable in tools/retis_in_container.sh to point to an alternate location for the retis container image for use by those in disconnected environments.
=> Added RETIS_IMAGE environment variable for alternate image location

retis-events/src/skb.rs, retis/src/module/skb/bpf.rs
While reverse ARP is quite old and note widely used, there are setups where it can still be seen; e.g. live migration of VMs. Let's not silence those ARP packets.
=> events: skb: add RARP support

retis/src/collect/collector/ct/bpf/ct.bpf.c, tests/test_ovs.py
Zone id is 16-bit, but for some reason is casted to u8 on read. This makes retis report incorrect values.
Fixes: e883af89e368 ("module: add conntrack module")
=> collector: ct: fix truncation of zone id

docs/install.md, tools/retis_in_container.sh
PAGER and NOPAGER can be used to control how retis pages stdout. Make them available inside the container.
=> tools: retis_in_container: use PAGER and NOPAGER

Vagrantfile, retis/src/module/skb/bpf/include/if_vlan.h, tests/conftest.py, tests/test_skb.py
Fixes https://github.com/retis-org/retis/issues/479
How to test:
```
cd tests
python3 -m flake8 && python3 -m pytest test_skb.py
```
Also fixed the issue that can be seen in:
https://cirrus-ci.com/task/6381925075517440?logs=up#L717
that issue didn't block the CI lane but nevertheless caused an error when bringing up the centos8 vagrant box
=> Add basic tests for VLAN

docs/collectors/ct.md, retis-events/src/ct.rs, retis/src/bindings/ct_uapi.rs, retis/src/collect/collector/ct/bpf.rs, retis/src/collect/collector/ct/bpf/ct.bpf.c
Extend ct and ovs events respectively with `ct->status`, and action address while executing.
Edit: I decided to drop the ovs patch for the time being as we have other work pending in that area.
Can be easily resurrected in a later moment.
=> Extend ct and ovs events 

retis/src/collect/collector/ovs/bpf/kernel_enqueue.bpf.c, retis/src/core/probe/builder.rs, retis/src/core/probe/kernel/bpf/include/common.h, retis/src/core/probe/kernel/bpf/include/retis_context.h, retis/src/core/probe/kernel/kprobe.rs, retis/src/core/probe/kernel/kretprobe.rs, retis/src/core/probe/kernel/raw_tracepoint.rs, retis/src/core/probe/manager.rs, retis/src/core/probe/probe.rs, retis/src/core/probe/user/usdt.rs
The retis context contains enough information to access common types such as the `sk_buff` pointer.
Sometimes this information cannot be easily available through the probe's arguments. In such cases, the context needs to be dynamically extended.
Well known types to `sk_buff` indirection can be implemented in the core so that it can be used in generic probes. However, this might be insufficient for some specific probes, for which a freplaced hook is available.
Note the hook is currently unused, the first user will be #493
=> Support context extensions

docs/filtering.md
=> doc: fix typo in expression

retis/src/cli/cli.rs, retis/src/collect/cli.rs, retis/src/collect/collect.rs, retis/src/generate/completion.rs, retis/src/helpers/logger.rs, retis/src/inspect/inspect.rs, retis/src/main.rs, tools/retis_in_container.sh
This is the natural follow up of #464 , and as discussed in https://github.com/retis-org/retis/pull/493#discussion_r1954898672
This PR merges the two-struct model into a single `RetisCli` struct and moves some top-level options down the relevant sub-commands.
=> Clean cli internal structures

Containerfile, tools/retis_in_container.sh
The removal of the `--kconf` root level option in #500  lead to some issues, namely:
- The `Containerfile` was not updated and this lead to generating incompatible images.
- The container script is linked from our documentation but does not work anymore for older images, including the current stable one.
- A syntax error could be seen while running the script.
Another potential issue would be running newer images while using the old container script. IMO that's not ideal but probably OK. If we want, we could add a hidden top level `--kconf` option and match it to display an error message, e.g. "option was removed, please update your script". I have not done that here as I'm not 100% convinced.
=> Container kconfig fixes

retis/src/collect/collector/ovs/bpf/include/ovs_operation.h
Remove the barrier_var() as this seems to alleviate the issue on Rawhide.
There's still the potential to break the verification on the previous versions of clang as this was introduced exactly for that.
Let's check this giving it a spin of functional tests.
=> ovs_operation: fix load issue in Rawhide

Vagrantfile
https://issues.redhat.com/browse/FDP-1243 was fixed, therefore remove the workaround for CentOS 10 test setups in the Vagrantfile.
=> Remove CentOS 10 OVS workaround in Vagrantfile

.codecov.yml
Let's avoid file-by-file summaries as those could always be consulted on the coverage site.
Also, let's set require_changes meaning:
"Only post comment if there are changes in coverage (positive or negative)"
The option `require_changes: true` was intentionally omitted in the first push to show how the new layout would look like.
=> codecov: update GH comment conf

retis-events/src/time.rs, retis/src/process/cli/pcap.rs
Timestamps in pcapng generated with the pcap command are essentially broken.
The series fixes both a resolution problem and applies the offset from the startup event.
Now the timestamps look reliable compared to captures taken in parallel.
=> Pcap fix timestamp

retis/profiles/drop.yaml, retis/src/collect/collect.rs, retis/src/core/probe/kernel/kernel.rs, retis/src/core/probe/kernel/probe_stack.rs, retis/src/core/probe/kernel/utils.rs, retis/src/core/probe/manager.rs, retis/src/core/probe/probe.rs, retis/src/process/cli/pcap.rs
Had this old patch hanging locally.
RFC as I'm mostly sending it as it was (just rebased).
- it's in addition to the stack option but can be as an alternative to those (e.g. --stack-list ... conflicting with the others)
- It's a global option remapped per-probe (we have to take into account automatic probes)
Some remarks:
- it doesn't formally check whether the symbol exists (we can extend it to do it, but I'm not sure what the advantage is), but just the syntax (consistency with the `-p`)
- even with the former bullet, it would be possible to specify an unprobed but existing symbol. 
The last bullet would implicitly cover the probe existence check but would require a bit of special casing.
I don't have a strong preference for the previous remarks (e.g. whether special casing while …
=> Stack trace filter

Cargo.lock, retis/Cargo.toml
Upstream release notes / changelogs: https://github.com/libpnet/libpnet/releases/tag/v0.35.0
While this is a SemVer-breaking update for `pnet_packet`, it doesn’t appear that any code changes are required, and `make test` and `make pytest` still pass.
=> Update pnet_packet to 0.35

docs/install.md, docs/limitations.md, docs/requirements.md, retis/src/collect/cli.rs, retis/src/collect/collect.rs, retis/src/core/inspect/kernel.rs, retis/src/core/kernel/symbol.rs, tools/retis_in_container.sh
Initially tracefs was part of debugfs and only accessible when debugfs was mounted. However this changed and tracefs can now be mounted even if debugfs is not. This is now a common behavior by default in many distributions.
This is indeed better; in Retis try using the standalone tracefs mount instead of the nested one.
=> tree: use tracefs instead of debugfs when possible

retis/src/collect/collect.rs
"-c | --collectors <COLLECTORS" can be specified more than once, and duplicates might arise, e.g: specifing a collector that was already added by a profile.
OTOH, it doesn't make sense to initialize the same collector more than once internally (and it actually causes all kinf of errors). E.g: `retis collect -c skb,skb` fails quite badly.
Deduplicate the collectors list before initializing them.
=> collectors: fix duplicated collectors

retis/src/core/filters/meta/filter.rs
Simple, plain fix. Initially part of #541 posted separately for convenience (v1.6 release)
=> filter/btf: fix array issue due to wrong jump offset

.cirrus.yml
The change forces a reboot after system updates to ensure tests run against the latest kernel version.
=> CI: ensure testing against up-to-date kernels

retis/src/core/probe/kernel/raw_tracepoint.rs
Cookie support in raw tracepoints was done looking at if the bpf_get_attach_cookie_tracing type existed, but this[1] actually precede the introduction of the raw tp cookie support. Fix this by also checking if the cookie field exist in the bpf_raw_tp_link struct instead, which was introduced as part of the raw tp cookie support[2].
Fixes #560.
[1] 2fcc82411e74 ("bpf, x86: Attach a cookie to fentry/fexit/fmod_ret/lsm."). [2] 68ca5d4eebb8 ("bpf: support BPF cookie in raw tracepoint (raw_tp, tp_btf)
programs").
Fixes: d55a7f759dd1 ("core: probe: kernel: set the symbol address in the BPF cookie").
=> probe: raw_tp: fix cookie support detection

retis-events/src/packet.rs
The option len field of the geneve header is expressed in 4-byte multiples.
=> retis-event: fix geneve opts_len printing

docs/events/nft.md
Handle 165 is "filter_INPUT", not "filter_PREROUTING" in this example.
Fixes: 383b8325df7a ("docs: modules: add a section on the nft collector")
Signed-off-by: Guillaume Nault <guillaume.nault@wanadoo.fr>
=> docs: Fix netfilter chain name (filter_INPUT).

docs/limitations.md
This is no longer true since we're parsing the packet in userspace. Packets will be captured from the MAC or network offset in all cases up until the limit or skb len, not metadata from in-kernel parsing.
=> docs: remove limitation on early probes

docs/CONTRIBUTING.md
None of those two labels exist anymore.
=> doc: contributing: remove issue links
