src/core/user/proc.rs

When parsing a process we're looking for all shared libraries mentioned in /proc/<pid>/maps. The issue was we were only rejecting paths matching the process one, and letting various files which where not actually a shared library. This become an issue when entries like /dev/zero where found as we ended up endlessly reading those until we were killed by the oom. This was the case when running our runtime unit tests as when a program loads an eBPF object, /dev/zero is found in its maps file.
Fix this by reworking the shared library detection.

Fix the shared library detection logic to avoid being killed by the oom

---

src/module/skb/bpf/skb_hook.bpf.c

Thanks to commit 09ddb6e9f1c8 spotted a type issue in the skb module hook.

module: skb: bpf: fix event struct type

---

src/core/events/bpf.rs
src/core/probe/kernel/kernel.rs
src/core/probe/user/user.rs
src/module/skb/skb.rs
src/module/skb_tracking/skb_tracking.rs

Implement unmarshalers as a Trait and remove their global cache

---

src/core/user/proc.rs

The core::user::proc::tests::get_threads test might fail sometime due to timing issues, if the thread isn't created fast enough. Fix this by ensuring the thread was started before running the test statements.
To avoid having 2 channels, use a simple Arc<Mutex<>> construction. This should be OK for test purposes.

core: user: proc: fix get_threads test

---

src/module/skb/bpf.rs
src/module/skb/event.rs
src/module/skb_drop/event.rs

Some skb modules fixes

---

src/core/user/proc.rs

The `core::user::proc::tests::get_threads` test sometimes failed. It turns out `get_thread_info` could throw errors when the expected file/dir tree was a bit off (no such file or directory).

Fix core::user::proc::tests::get_threads test

---

Cargo.lock
Cargo.toml
src/process/cli/sort.rs

Also resolves a dependabot  moderate CVE alert.

tree: update dependencies

---

RELEASE.md

This should be merged only after the first release is out.

Add a release checklist

---

README.md
src/collect/collector.rs
src/core/inspect/check.rs
src/core/inspect/kernel.rs
src/core/probe/kernel/bpf/include/helpers.h
src/module/nft/nft.rs
src/module/ovs/ovs.rs

Fixes #207. Details in the commit messages.

Support more kernel configuration locations

---

src/core/inspect/kernel_version.rs

Current KernelVersion seems to assume that, after the os build version directly follows the minor version, e.g: 6.2.14-300.fc38.x86_64.
However, that is not true for some OSs, such as arch whose kernel versions look like 6.4.12-arch1-1.
This patch tries to find the first parseable number in the trailing '-'separated strings and uses that as build number.
Fixes: #241

core: inspect: make kernel version work with arch

---

src/module/skb_drop/bpf/skb_drop_hook.bpf.c

The previous fix wasn't complete and in case a kernel was supporting drop reasons but the hook was attached to a probe not having access to one, empty zeroed event sections were still reported.

module: skb_drop: do sent empty event sections

---

src/module/ct/bpf.rs
src/module/ct/bpf/ct.bpf.c

A few fixes for the ct module.

module: ct: some fixes

---

src/module/skb/bpf/skb_hook.bpf.c

Same as 1bb047ba166b ("module: skb: bpf: fix verifier issue on older kernels") but that had a flaw and was broken by a recent change that fixed it.
Could not find a better way. If not using &= no size check works. This has the downside of limiting the capture size of L3-only packets to 0x7f; but that is not that bad. Many packets headers should be within that limit. Another working solution would be to increase our buffer size to `PACKET_CAPTURE_SIZE + sizeof(ethhdr)`, which allows to capture up to PACKET_CAPTURE_SIZE of data in each case.
Fixes: 3afddf5ef4fa ("module: skb: fix raw packet retrieval for max capture size")

module: skb: fix (again) skb hook for old kernels

---

Cargo.lock
Cargo.toml
retis-derive/Cargo.toml
src/core/probe/kernel/bpf/include/common.h
src/core/tracking/skb_tracking.rs
src/main.rs

Including a few last changes (btf-rs, one small improvement and one fix).

Release 1.3

---

.cirrus.yml
Vagrantfile
src/process/series.rs

CI: add c8s runtime tests & upgrade Fedora version

---

src/module/skb/bpf/skb_hook.bpf.c
src/process/series.rs

Fixes #320.
Lengthy explanation in both commit messages.

Improve raw packet retrieval (verifier workaround & fix)

---

src/core/kernel/symbol.rs
src/module/nft/nft.rs
src/module/ovs/ovs.rs
src/process/series.rs

Improve symbols validation

---

build.rs

Since #237 the BPF part is not handled by `cargo build` anymore. Users who are not aware of this and run `cargo build` directly will get error:
```
--- stderr
thread 'main' panicked at build.rs:46:9:
failed to generate `src/core/probe/kernel/bpf/.out/kprobe.bpf.o`
Caused by:
0: Failed to generate skeleton for src/core/probe/kernel/bpf/.out/kprobe.bpf.o
1: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The users could not get what should do to avoid this error. Let's add an error hint so they can know how to avoid it. Here is what it looks like:
```
--- stderr
thread 'main' panicked at build.rs:48:17:
Unable to find src/core/probe/kernel/bpf/.out/kprobe.skel.rs, please try 'make ebpf' first
note: run with …
```

build.rs: add error hint when build before making ebpf

---

docs/index.md
src/core/filters/meta/bpf/include/meta_filter.h

A clean-up chore removing unneeded check.

remove bound check in meta filter

---

docs/resources.md
mkdocs.yml

Listing blog posts, presentations, etc.

doc: add a page on external resources

---

Makefile
build.rs
ebpf.mk

- Introduces some rough ARCH logic (instead of the previous always hard-code value detached from the Rust build)
- Addresses the requests not covered during the first introduction of the Makefile.

Makefile clean up and improvements

---

Vagrantfile
src/core/events/bpf.rs
src/module/ovs/bpf.rs
src/module/ovs/bpf/kernel_exec_tp.bpf.c

Haven't went deep into the why here, but this fixes our runtime CI.

Fix OvS runtime CI failure

---

src/collect/collector.rs
src/core/events/bpf.rs
src/core/events/bpf/include/events.h
src/core/filters/meta/bpf/include/meta_filter.h
src/core/probe/bpf/include/common_defs.h
src/core/probe/kernel/kprobe.rs
src/core/probe/kernel/kretprobe.rs
src/core/probe/kernel/raw_tracepoint.rs
src/core/probe/user/usdt.rs
src/main.rs

Add a dedicated trace pipe for better debugging eBPF progs and signaling unexpected errors.

Bpf logger

---

docs/index.md
src/core/filters/meta/bpf/include/meta_filter.h
src/core/filters/meta/filter.rs
src/core/probe/bpf/include/common_defs.h

Adds bitfield support for LE ARCH

Meta bitfields

---

Makefile

fix install target.

---

Cargo.lock
retis/Cargo.toml

Cargo.toml: remove bimap from the dependencies

---

AUTHORS.md
retis/src/core/inspect/btf.rs

sync AUTHORS.md with the current state

Update AUTHORS.md with the latest contributors

---

retis-events/src/display.rs
retis-events/src/net.rs
retis-events/src/skb.rs
retis/src/module/skb/bpf.rs
retis/src/module/skb/bpf/skb_hook.bpf.c

Better handle packets we don't recognize

---

.gitattributes

- path was no longer valid
- added some more files

Fix GH languages stats

---

retis-events/PYTHON_LIB_README.md

Example code simply does not work.

events: fix python library README.md

---

retis/src/core/probe/kernel/raw_tracepoint.rs
retis/src/core/probe/user/usdt.rs

A segmentation fault can happen when exiting Retis collection when using USDT. This is because the underlying USDT object was already freed as we did not keep it.
Fix this by keeping the skel alive during the collection. For some reason this did not occur for raw tracepoints, but for completeness also do the change there.
Fixes #475.

core: probes: fix segfault on exit

---

retis/src/bindings/ovs_common_uapi.rs
retis/src/module/ovs/bpf/include/ovs_common.h

- Fixes #478 
- refreshes the bindings removing a leftover

Binding generation fix

---

AUTHORS.md

Thanks to the three new contributors!

[chore] Update AUTHORS.md

---

.cirrus.yml
Vagrantfile

Add CentOS 10 Stream to CI

---

.cirrus.yml
.codecov.yml

Upload coverage data to Codecov and consume the service

Add codecov support

---

docs/index.md
retis/profiles/generic.yaml
retis/src/collect/cli.rs
retis/src/collect/collect.rs

This fixes issues and inconsistencies. Details in the commit messages.

Remove the "auto-mode" concept

---

Vagrantfile
retis/src/collect/cli.rs

Pre-release fixes.
Includes:
- CLI fix
- C9S CI fix

cli/collect: do not accept invalid parameters

---

docs/resources.md

A new blog post is available, add it to the list.

docs: add filtering blog post
